[gcp_service_account]

type = "service_account"

project_id = "dimna-dss"

private_key_id = "be7c891ff9f11f31b95dbc11a1a35e75db3a0598"

private_key = """
-----BEGIN PRIVATE KEY-----
\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC3l4jTfNteIvAp\noZGg4rVU4fDTP4x1oqVie+0p56pYfq2n/di2ImHdXfztZGgsFKg+7bZJHx17HWUX\nOLnLIq4xUAN9bI9mI4w243I4Z2MoPVIAgeeWYbJeHlyJ6IIbZQNZQupnwvJ52COJ\npOczcu1KBn2JCGdvSmE2gGUOD/+hpZk2IOFAfVcYuKIDXUmrDrCjB6/88eOq04FH\nP3NfNtIKHqtTpVPftC+qtfy637Ufo06rEj82WUPDR5zJfIPDc8L76SQZt1dJyPOC\no6W/WH0D3HPudM7hGKzGUKlPWbbuhyR0oMogwvXiQG/6m5YDG8V0uGor/y3Z+7Xu\nuRPKXZozAgMBAAECggEAAfnyIaCy9dj3b+NK34oBPLgv8P46o1uMXzqJS42wYkJ+\n2ROc/Rzyo8Dqw510l6DjTMYfU7svhI9E8tKMAXlOmb5MQ1HjW0yfqkmZhazrPtgm\nJVZAqXhExMmb4mor2GKmfhP/1P0ewhwHCejKCl4+2rCmMk7yWhrZYA5SyCt464MJ\nq0x4tYiHDOjYRqknm0cBzSiGM+8FdVDSqNgY8kN2lKQ8liSLEderpYJp7WposNwH\n9erlvHeuO0c05HV37/IOzPHHF4YJFagpYkdDZUpc41x1Ci/wqIBDowPEvXiZZWZX\ngR/Udop8p2lBZv/khySJBKjbPF90hfR6b02Q0Br9cQKBgQDsaXMX7Qq3TAuc/ggB\nJIHIukjCfU9zNbDvcHiFk50Uj6jgYJCdbGe/Iu4MqpbIBUQ7iqKY3pjyZ7RBBVQP\nFP+jQvFOlh6mR9uVCfcrWUOS2Iw7pG6Atq79tThZ1Ay0V/BvfVH8IgxlnCW7DDRs\nzVtZtm84fCJS0JtjNkkl1HlSwwKBgQDGzbdmQzbnH/2weL+vyOnFMhuCGzi0MNCS\nUpoCh2pC+VjcxgnuX291ugQDuFmUSRmm1KY0c+dA3McBK/zEuVdeUMxG+x0Y5eW7\n7jAiYopq54OZ2NGQl0zJRe0JiyTHzgU7yDIbVOlLL3VPDjpWX6OyP9+jivZ5o/SX\nvmyfKDhD0QKBgQDmZvLba5KZB0z+KPmmG209Mof8vGG1F6uj/4oGLNHXGxdr7dCj\nC+akeidkQtEGiVNxb/B9advHy1f6UnYU6NMnyvMgMuAWEEwpmXfBUJKxx8gLzHpB\niUlMS9Rqf2YOUPIrxggj4Q8R7Dc9b2ycaRtReKI2e4x8B4CZFWv+qW/APwKBgHas\nwvhm01VxQW2hBzyWQQaYfNdUDKt0IG3YpVsxHvvQAX35MmB70/uBCXh3CfJ9GLUA\naB8TuU58/Mb0TTXaNg91SBxvNtVwF43yCAXesSZUAblLNv6LcykLdw6lY1Vq5LDl\nNxQdwg5BzFNe+PAqs3tqqcPk5nGCsDYNVKZFyiChAoGAHnAUnhHbBuTOhnYqmk8D\n+5/sx+UcqOhO96C1L1mi9PPTWhEwgOeVnhENWsn6+5X6TNKd9RSmWbdNtGfgf/Kv\nUaDfNr9pta204OgcVSvv/bT9QsBKV3Bypl8XnolLXCKxlMIjiBZtHzbVt6/e4rqL\nSC26IaU63xUAmZFc4l1akT0=\n
-----END PRIVATE KEY-----
"""

client_email = "dimna-dss@dimna-dss.iam.gserviceaccount.com"

client_id = "111959802592592509215"

auth_uri = "https://accounts.google.com/o/oauth2/auth"

token_uri = "https://oauth2.googleapis.com/token"

auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"

client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dimna-dss%40dimna-dss.iam.gserviceaccount.com"

universe_domain = "googleapis.com"
